language: java
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE aga;'
- mysql -e 'USE aga;CREATE TABLE `undeads` (
  `id` int(11) NOT NULL,
  `nazwa` varchar(250) DEFAULT NULL,
  `zycie` int(11) DEFAULT NULL,
  `sila` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
script:
- cd nieumarli
- mvn clean test
